apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    # Must match the label of pod
    app: webapp
    release: "0-5"
  ports:
    # Exposes the pod to minikube_ip:30080
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort