apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    # Must match the selector of service
    app: webapp
    release: "0"
spec:
  containers:
  # Specifies the container to use inside this pod
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

  apiVersion: v1
  kind: Pod
  metadata:
    name: webapp-release-0-5
    labels:
      app: webapp
      release: "0-5"
  spec:
    containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5